- id: no-push-wip-commits
  entry: no-push-wip-commits
  name: do not push WIP commits
  description: prevents WIP commits from being pushed
  language: python
  stages: [push, manual]
- id: no-push-squash-commits
  entry: no-push-squash-commits
  name: do not push squash/fixup commits
  description: prevents squash! or fixup! commits from being pushed
  language: python
  stages: [push, manual]
